first part
EvgeniyD1/services pull request #1
Opened 2023-06-14 14:10 UTC by EvgeniyD1

added the main entities, controllers, services and mappers, also implemented security based on the jwt token

2023-06-15 13:54 UTC, skalashynski requested changes

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/aspect/ServiceLogAspect.java
> +                + " finished. Method execution time: " + sw.getTotalTimeMillis() + " milliseconds.");
Pls use `debug` for logging. This kind is absolutely not info

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/resources/application.properties
> +spring.datasource.password=root
Use env vars

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/resources/application.properties
> +LIFE_TIME=86400000
Incorrect var name `LIFE_TIME`

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/resources/application.properties
> +logging.level.com.example.main_service.mapper.ArticleMapper=TRACE
Not sure about `trace` for mappers

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/controller/ArticleController.java
> +    }
what if no article is found? which HTTP status should be returned?

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/config/JwtTokenFilter.java
> +        filterChain.doFilter(request, response);
If the is no token, why do you go later? why do you call `doFilter`?

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/controller/ArticleController.java
> +    }
what if no article is found? which HTTP status should be returned?

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/controller/RegistrationController.java
> +        userService.insertUser(request);
you have to save all username with the lower_case and validate respectfully.

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/mapper/ArticleMapper.java
> +
Is it possible to return `Optional<Article>`?

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/service/ArticleService.java
> +        article.setCreationDate(new Date());
setCreationDate -> setCreationDateTime

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/service/ArticleService.java
> +        Article article = new Article();
Let me know, how do you open transaction?

2023-06-15 13:54 UTC, skalashynski commented on main_service/src/main/java/com/example/main_service/service/UserService.java
> +        user.setRegistrationDate(new Date());
use datetime

2023-06-15 14:54 UTC, EvgeniyD1 commented on main_service/src/main/java/com/example/main_service/aspect/ServiceLogAspect.java
> +                + " finished. Method execution time: " + sw.getTotalTimeMillis() + " milliseconds.");
what I should do?

2023-06-15 14:57 UTC, EvgeniyD1 commented on main_service/src/main/java/com/example/main_service/domain/Article.java
> +    private Date creationDate;
fixed

2023-06-15 14:58 UTC, EvgeniyD1 commented on main_service/src/main/resources/application.properties
> +LIFE_TIME=86400000
it's jwt token lifetime

2023-06-15 14:59 UTC, EvgeniyD1 commented on main_service/src/main/java/com/example/main_service/MainServiceApplication.java
> +@EnableTransactionManagement(proxyTargetClass = true)
in's need to work  @PreAuthorize()

2023-06-15 14:59 UTC, EvgeniyD1 commented on main_service/src/main/resources/application.properties
> +spring.datasource.password=root
fixed

2023-06-15 15:01 UTC, EvgeniyD1 commented on main_service/src/main/resources/application.properties
> +LIFE_TIME=86400000
what does that mean in this case?

2023-06-15 15:01 UTC, EvgeniyD1 commented on main_service/src/main/resources/application.properties
> +logging.level.com.example.main_service.mapper.ArticleMapper=TRACE
ok

2023-06-15 15:08 UTC, EvgeniyD1 commented on main_service/src/main/java/com/example/main_service/config/JwtTokenFilter.java
> +        filterChain.doFilter(request, response);
ok, what i should to do?

2023-06-20 18:40 UTC, skalashynski approved these changes

2023-06-20 18:41 UTC, merged